name: Node.js Docker Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t ashanknimsara/ecommerce-microservices-devops:latest .

      - name: Print Docker credentials
        run: |
          echo "Dockerhub Username: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Dockerhub Token: ${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Print Azure credentials
        run: |
          echo "Azure Client ID: ${{ secrets.AZURE_CLIENTID }}"
          echo "Azure Tenant ID: ${{ secrets.AZURE_TENANTID }}"
          echo "Azure Subscription ID: ${{ secrets.AZURE_SUBSCRIPTIONID }}"

      - name: 'Azure PowerShell login with subscription'
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: Push Docker image to Docker Hub
        run: docker push ashanknimsara/ecommerce-microservices-devops:latest

      - uses: azure/aks-set-context@v3
        with:
          resource-group: 'ecommerce-microservices-devops'
          cluster-name: 'nodedeploy'

      - name: Apply Kubernetes manifests
        run: kubectl apply -f ./path/to/your/k8s.yml
